nav:
  Home: /
  All: /archives/
  React: /tags/React/
  Angular: /tags/Angular/
  JavaScript: /tags/JavaScript/
  数据结构与算法: /tags/数据结构与算法/
  #Projects: http://github.com/gabithume

projects_url: https://github.com/chen-zhi

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/chen-zhi
        # twitter: /
        # facebook: /
        linkedin: https://www.linkedin.com/in/zhi-chen-003875108/
    show_all_posts: false
    post_count: 5
    highlight: monokai

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
